name: Feature Shaping
description: Use this template to discuss implementation.
title: "shape: "
labels: ["shaping"]
projects: ["mktcode/4"]
assignees:
  - mkcode
body:

  - type: markdown
    attributes:
      label: Product Impact
      description: How does this affect the product? Why is this important?
      placeholder: Better performance!
      value: 'Hi!'
    validations:
      required: true

  # - type: checkboxes
  #   attributes:
  #     label: Category
  #     description: What kind of changes are needed?
  #     options:
  #       - label: Refactoring
  #       - label: Implementation
  #       - label: Chores
        
  # - type: markdown
  #   label: Checklist
  #   attributes:
  #     value: |
  #       - [ ] What is the maximum time we want to spend on this?
  #       - [ ] Is the scope clearly defined and aligned with that? Any tradeoffs?
