name: Feature Shaping
description: Use this template to discuss future changes.
title: "shape: "
labels: ["shaping"]
projects: ["mktcode/4"]
assignees:
  - mkcode
body:

  - type: textarea
    id: product-impact
    attributes:
      label: Product Impact
      description: How does this affect the product? Why is this important?
      placeholder: Better performance!
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Category
      description: What kind of changes are needed?
      options:
        - label: Refactoring
        - label: Implementation
        - label: Chores

  - type: markdown
    attributes:
      value: |
        # Checklist

        All these questions should have been answered, before moving to implementation:
        
        - [ ] What is the maximum time we want to spend on this?
        - [ ] Is the scope clearly defined and aligned with that? Any tradeoffs?
